special card functionality added & tested with 4test levels
kalinchan/DC2TRP-Team-Project pull request #44
Opened 2023-06-03 20:36 UTC by chelseahouston

2023-06-03 21:16 UTC, cameron-barker-goodyear requested changes
The functionality of the special cards work

however sadly, some issues:

- The x isn't showing on the enemy when clicking on the defence or special cards but it is showing for attack cards



- end of level card is not displaying:
![image](https://github.com/kalinchan/DC2TRP-Team-Project/assets/101347655/a95cad01-1be4-4324-92df-c61aebb05eeb)



- Also the special cards have a couple issues(well maybe not sure if its intened), the special cards are showing in the deck when the deck if refreshed. Another one which may or may not be an issue, is special cards are apprearing accross levels
![image](https://github.com/kalinchan/DC2TRP-Team-Project/assets/101347655/c264cd9e-145f-4359-9bf7-73559ca19c6b)

     If the first is an issue, i assume this would be as well

2023-06-03 21:24 UTC, chelseahouston commented
Ah I see, the card prefabs were altered in a previous commit and just needs dragging back in to the EOL screen. It's something I can sort quickly tomorrow. Same with the X for the enemy (good catch I missed that!)

The cards are supposed to appear across levels, they get added incrementally (level 2 adds card1, level 3 adds card2 (and card1) etc). The scene in the screenshot you've attached is level 3 that should have 2 special cards (as seen, so seems to be working as expected). 

When you say they appear when the deck is refreshed, are you referring to level 1?

2023-06-04 15:10 UTC, TheCherubQueen approved these changes
Literally watched Chelsea fix these and run through them. 

All seems good

2023-06-04 15:11 UTC, TheCherubQueen approved these changes

2023-06-04 15:12 UTC, merged